services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9001:9000"
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    image: nginx
    container_name: server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - laravel
  #    environment:
  #      - NGINX_HOST=foobar.com
  #      - NGINX_PORT=80

  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: parser
      MYSQL_USER: parser_user
      MYSQL_PASSWORD: parser_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - laravel
volumes:
  db_data:

networks:
  laravel: